[package]
name = "sample-project"
version = "0.1.0"
authors = ["Ryosuke Kamesawa <ryosuke.kamesawa@dena.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.0"
